site_name: Gears Docs
site_url: https://dm4ml.github.io/gears/
repo_url: https://github.com/dm4ml/gears
docs_dir: docs
repo_name: dm4ml/gears
remote_branch: gh-pages
nav:
  - Getting Started:
      - Welcome: index.md
      - Quickstart: quickstart.md
  - Documentation:
      - Overview: overview.md
      - Primitives: primitives.md
      - Examples:
          - Text to SQL (Simple): examples/simple.md
          - Personalized Vacation Planner (Advanced): examples/advanced.md
          - Custom LLMs: examples/customllm.md
          - Utils: examples/utils.md
  - API Reference:
      - gears: api/gears.md
      - history: api/history.md
      - llms: api/llms.md
      - utils: api/utils.md

theme:
  name: material
  icon:
    logo: fontawesome/solid/gears
    repo: fontawesome/brands/git-alt
  favicon: images/logo.png
  extra_files:
    - images/
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue
      accent: orange
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: blue
      accent: orange
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: Ubuntu
    code: Ubuntu Mono

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
    - toc.integrate
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings
  - autorefs

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
